#!/bin/bash

TOOL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOME=$(realpath "$TOOL_DIR/..")

stack build brittany
find $PROJECT_HOME -not -path '*/.*/*' -name '*.hs' | \
    xargs stack exec brittany -- --check-mode