#!/bin/bash

TOOL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOME=$(realpath "$TOOL_DIR/..")

cd "$PROJECT_HOME" # to find brittany.yaml
stack build brittany
find $PROJECT_HOME -not -path '*/.*/*' -name '*.hs' | \
    xargs stack exec brittany -- --write-mode=inplace $@
