#!/bin/bash
TOOL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOME=$(realpath "$TOOL_DIR/..")

cd "$PROJECT_HOME"
STATUS="$(git status --porcelain)"
if [ -n "$STATUS" ]; then
    echo "$STATUS"
else
    "$TOOL_DIR/format"
    "$TOOL_DIR/refreeze"
    cabal build
    cabal run myml-test
fi
