#!/bin/bash

TOOL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOME=$(realpath "$TOOL_DIR/..")

cd "$PROJECT_HOME"
mv cabal.project.freeze cabal.project.freeze.old
cabal freeze
diff cabal.project.freeze cabal.project.freeze.old
