#!/usr/bin/env bash

set -e

TOOL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_HOME=$(realpath "$TOOL_DIR/..")

cd "$PROJECT_HOME"

cabal run myml-test
"$TOOL_DIR/test-sources" "$PROJECT_HOME/stdlib"
"$TOOL_DIR/test-sources" "$PROJECT_HOME/examples"
