name: Build

on: [push]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        ghc: [ '8.6.5', '8.8.3' ]
        cabal: [ 'recommended' ]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # force rebuild all caches once a month
    - name: Get date
      id: get-date
      run: echo "::set-output name=date::$(date +'%Y-%m')"

    - name: Cache ~/.ghcup
      uses: actions/cache@master
      with:
        path: ~/.ghcup
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-ghcup-${{ steps.get-date.outputs.date }}

    - name: Cache ~/.cabal/packages
      uses: actions/cache@master
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-cabal-packages-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-cabal-packages-${{ steps.get-date.outputs.date }}-

    - name: Cache ~/.cabal/store
      uses: actions/cache@master
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-cabal-store-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-cabal-store-${{ steps.get-date.outputs.date }}-

    - name: Cache dist-newstyle
      uses: actions/cache@master
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-dist-newstyle-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-dist-newstyle-${{ steps.get-date.outputs.date }}-

    - name: Setup ghcup
      run: |
        mkdir -p ~/.ghcup/bin
        curl https://gitlab.haskell.org/haskell/ghcup/raw/master/ghcup > ~/.ghcup/bin/ghcup
        chmod +x ~/.ghcup/bin/ghcup
        echo "::add-path::~/.ghcup/bin"

    - name: Setup haskell
      run: |
        ghcup install ${{ matrix.ghc }}
        ghcup set ${{ matrix.ghc }}
        ghcup install-cabal ${{ matrix.cabal }}

    - name: Cabal update
      run: cabal v2-update

    - name: Build
      run: |
        cabal v2-configure
        cabal v2-build

    - name: Run tests
      run: cabal v2-run myml-test

    - name: Install mymli
      run: |
        mkdir -p bin
        cabal v2-install mymli --installdir=bin --install-method=copy

    - name: Upload mymli executable
      uses: actions/upload-artifact@master
      with:
        name: mymli-${{ runner.os }}
        path: bin

  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Check format
      run: ./tools/format --check-mode

  specification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: xu-cheng/latex-action@master
      with:
        root_file: spec/specification.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -output-directory=spec

    - name: Upload PDF file
      uses: actions/upload-artifact@master
      with:
        name: specification
        path: spec/specification.pdf
