name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Check format
      run: ./tools/format --check-mode

    - name: Setup Haskell
      uses: actions/setup-haskell@master

    - name: Cache ~/.cabal/packages
      uses: actions/cache@master
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-cabal-packages-${{ hashFiles('**/cabal.project.freeze') }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@master
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-cabal-store-${{ hashFiles('**/cabal.project.freeze') }}

    - name: Cache dist-newstyle
      uses: actions/cache@master
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-dist-newstyle-${{ hashFiles('**/cabal.project.freeze') }}

    - name: Cabal update
      run: cabal update

    - name: Build
      run: |
        cabal configure
        cabal build

    - name: Run tests
      run: cabal run myml-test
