name: Specification

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: xu-cheng/latex-action@master
      with:
        root_file: spec/specification.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -output-directory=spec

    - name: Upload PDF file
      uses: actions/upload-artifact@master
      with:
        name: specification
        path: spec/specification.pdf
